### ISSUE TITLE
Implement attach from external chains

### ISSUE THREAD

**Issue by alebaffa** [fragcolor-xyz/clamor#203]

**Comment by dougdot3** [comment]
Use case based on some initial potential projects for Narraio:

- An existing NFT projects wants to more deeply engage its community
- To do this, they want to create story for their project that the community can engage with
- Individual NFT holders can also create stories for their own characters

In this scenario, we would:
- Activate the 'collection'. (Solana has collections, I don't know exactly what they're called in ETH)
- When a user comes to the site, they connect their wallet and we search for NFTs whose collections have been activated
- We then create a proto to match the NFT. NOTE that when activating the collection, we probably want to also create a field conversion process? For example, we might have a format for character protos with a field for "name", but it might be called something else in the external NFT

Later, when a user wants to perform some action in Fragnova in which their proto plays a part, we would probably need some validation that they still own the original NFT.

**Future Use Case**
I can see future use cases where we want a straight import of an NFT. These would be cases where the collection isn't pre-validated.

What if someone wants to 'attach' their RTFKT avatar NFT to Fragnova? In theory, they could come to the site and ANY NFT in their collection can be attached. This would allow 'interoperability' with assets being brought in from other chains.

The process of importing in this case MIGHT include:

- Open wallet
- Attach ANY NFT
- Determine whether the NFT is part of a collection. If a collection proto (attribute? trait) doesn't exist, create one, so that even if individual users come and attach an NFT, we don't lose the fact it was part of a collection.
- Provide some sort of 'wizard' for converting fields to data
- Provide some sort of utility to attach/import other assets. More and more collections are releasing blender files etc

**Comment by sinkingsugar** [comment]
Thanks @dougdot3 that was the original intention, the only limit to keep in mind is that there can be only 1 proto ever. but I think it still makes sense, if not even more powerful cos NFTs are also unique.

**Comment by dougdot3** [comment]
> Thanks @dougdot3 that was the original intention, the only limit to keep in mind is that there can be only 1 proto ever. but I think it still makes sense, if not even more powerful cos NFTs are also unique.

Absolutely - which is why I mention validation, because you don't want owner #1 coming in and attaching, selling the original, and owner #2 coming and trying to attach to a different proto (he can't anyways).

But you're right - my Echocore example is such a one-off, where a collection may prefer to just migrate into Fragnova on a one-off basis and then not care what happens to the original NFT.

**Comment by aang114** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/clamor/203?planning-poker) with Zenhub @aang114 @alebaffa @sinkingsugar

**Comment by alebaffa** [comment]
I think it makes sense to split this issue in multiple sub-issues to address each specific technical piece of this story.

**Comment by alebaffa** [comment]
As discussed internally, I created an epic to track the work on this story: [https://github.com/fragcolor-xyz/clamor/issues/218](https://github.com/fragcolor-xyz/clamor/issues/218).
So, I am closing this issue, but its link will be anyway available in the epic description for record.

**Comment by sinkingsugar** [comment]
We closed this issue with 13 points attached but no work done.
Make sure you remove points in this case cc @ZerusD @Kryptos-FR

**Comment by sinkingsugar** [comment]
Also close as not planned is better, as it was not done.
